apiVersion: v1
kind: Service
metadata:
  labels:
    app: traefik-monitor
  name: traefik-monitor
  #namespace: default
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    name: metrics
  selector:
    component: maesh-mesh
  type: ClusterIP
