apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: traefik-monitor
  name: traefik-monitor
  #namespace: default
spec:
  endpoints:
  - interval: 30s
    port: metrics
    path: /metrics
    scheme: http
  selector:
    matchLabels:
      app: traefik-monitor
