apiVersion: v1
kind: Namespace
metadata:
  name: grzs-traefik
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: traefik
rules:
- apiGroups:
  - ""
  resources:
  - services
  - endpoints
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - "extensions"
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extensions
  resources:
  - ingresses/status
  verbs:
  - update  
- apiGroups:
  - "traefik.containo.us"
  resources:
  - middlewares
  - middlewaretcps
  - ingressroutes
  - traefikservices
  - ingressroutetcps
  - ingressrouteudps
  - tlsoptions
  - tlsstores
  - serverstransports
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: traefik
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: traefik
subjects:
- kind: ServiceAccount
  name: traefik
  namespace: grzs-traefik
---
apiVersion: v1
data:

  config.yaml: |
    providers:
      kubernetescrd:
        endpoint: https://kubernetes.default
        allowCrossNamespace: true
    api:
      dashboard: true
      insecure: true
    entryPoints:
      web:
        address: ":80"
      websecure:
        address: ":443"
    log:
      level: debug   
    accessLog:
      fields:
        defaultMode: "keep"
        names:
          defaultMode: "keep"
        headers:
          defaultMode: "keep"
kind: ConfigMap
metadata:
  namespace: grzs-traefik
  name: traefik
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: traefik
  name: traefik
  namespace: grzs-traefik
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      containers:
      - args:
        - --configFile=/etc/traefik/config.yaml
        image: hub.iefcu.cn/public/traefik:v2.5
        name: traefik
        ports:
        - containerPort: 8080
          name: admin
          protocol: TCP
        - containerPort: 80
          name: http
          protocol: TCP
        - containerPort: 443
          name: https
          protocol: TCP          
        volumeMounts:
        - name:  config
          mountPath: /etc/traefik
      volumes:
      - name: config
        configMap:
          name: traefik
      serviceAccount: traefik          
---
apiVersion: v1
kind: Service
metadata:
  name: traefik-ingress
  namespace: grzs-traefik
  labels:
    app: traefik
spec:
  ports:
  - name: https
    protocol: TCP
    port: 443
    targetPort: 443
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  type: NodePort 
  selector:
    app: traefik
  externalIPs:
  - 10.20.5.201
---
apiVersion: v1
kind: Service
metadata:
  name: traefik-admin
  namespace: grzs-traefik
  labels:
    app: traefik
spec:
  ports:
  - name: admin
    protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP 
  selector:
    app: traefik
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik
  namespace: grzs-traefik  
---
