---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: maesh
    component: coredns
  name: traefik-mesh-coredns-role
  namespace: kube-system
rules:
  - apiGroups:
      - ""
    resources:
      - endpoints
      - services
      - pods
      - namespaces
    verbs:
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: traefik-mesh-coredns
  namespace: kube-system
  labels:
    app: maesh
    component: coredns
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: traefik-mesh-coredns-role
subjects:
  - kind: ServiceAccount
    name: traefik-mesh-coredns
    namespace: kube-system
