apiVersion: v1
baseDomain: iefcu.cn
compute:
- hyperthreading: Enabled
  name: worker
  replicas: 0
controlPlane:
  hyperthreading: Enabled
  name: master
  replicas: 1
metadata:
  name: kcp5-arm
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  none: {}
fips: false
pullSecret: '{ "auths": { "hub.iefcu.cn": { "auth": "a3lsaW46a3N2ZDIwMjA=", "email": "iefcuxy@gmail.com" } } } '
sshKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDDvVrij+c3BDXGEkLEAUCPXzdJyESGYwWrH6N3+jdse55hb7oyGBMr3uup4dM4un2TXRxEi7N8apQcoV6UJgsBU9xVqCSZQZD/KREeVsHyLXb6HOc5lAdaWSwMpVJ/Z8TtXIpi4xnKGc5c7R6O15dzBmu/hsLJFRrX/h/k/QEVNANkF2jYr9SZzHG4WZQ189Rb+r5vk1aZTS9CXa6bYbWi5CRSyCzt3Ka8q5K7OvKg+ecY/273f1s9eGazaLi6XfMRpE6eGcCyKT7zl6bYR7CrAWaskDBMDZyw2t6SDLEUxwy7/oHzapAearOgyH37WEcV2tfeaiawCnJAHIlPjrT3 iefcuxy@gmail.com'
additionalTrustBundle: |
  -----BEGIN CERTIFICATE-----
  MIIGDTCCA/WgAwIBAgIUVbdKoHJhw9oaExhSJKtETTwKdjswDQYJKoZIhvcNAQEL
  BQAwgZQxCzAJBgNVBAYTAkNOMREwDwYDVQQIDAhTaGFuZ2hhaTERMA8GA1UEBwwI
  U2hhbmdoYWkxEjAQBgNVBAoMCUxvY2FsaG9zdDEUMBIGA1UECwwLSVQtRGV2LVRl
  c3QxEzARBgNVBAMMCiouaWVmY3UuY24xIDAeBgkqhkiG9w0BCQEWEWRldi10ZXN0
  QGllZmN1LmNuMCAXDTIyMDMwNjEyMjU0MVoYDzIxMjIwMjEwMTIyNTQxWjCBlDEL
  MAkGA1UEBhMCQ04xETAPBgNVBAgMCFNoYW5naGFpMREwDwYDVQQHDAhTaGFuZ2hh
  aTESMBAGA1UECgwJTG9jYWxob3N0MRQwEgYDVQQLDAtJVC1EZXYtVGVzdDETMBEG
  A1UEAwwKKi5pZWZjdS5jbjEgMB4GCSqGSIb3DQEJARYRZGV2LXRlc3RAaWVmY3Uu
  Y24wggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQCyevCAurcV4V3PP9Gl
  lZVjPWPOrrCgMySUqZ+riABMsKLXltqeAUxmosj/U4TIddwjdpmeioJZ0IWGT8MQ
  v5aGw9HrC7zsj/ML1yZ/34Y0gaK5haeAatSAse7AncW6pae0H13AnneAYhuE5Uch
  HyO0J9xR9zZUwrnn/BRESlvSfDMPma4wwwlwr4vagvYp+biH7qfWC/23BKa4Ijx/
  k7kyqh5ypuTVWHxMMn/aid4rsfrqQv5ComwVoTlFqPq1CSYZjKFxJvWxIYuuCvEw
  8I/vZazXNf3vJcQmzueVvDZXypfFkmQfTMHxt9nhdclJ6u6TV4+ppao/kKetdl4G
  VVrSj6KQUnbQKehe9qIPpoEsvZoxg+fpOwvJBGaVnwdbjEUaRGMM1NdL8ol7IXMK
  YGLpka1EbtQLbRsr2O1U9Uf/J3WON9ZoT3G7IPUo7BBtdMMgx8wkt9ki1joUd+g8
  QfI88jtc1b1TKJ6OH+1YAeHwOi+MpwgeRt0xUqESyOi/oAHuvKNRgk40XQE3Vieh
  tDSOwPd3AyKPbBPrEegNQvRHn/FsWZi9Nxjyb4JFSRzQup6niaSpLRGtqfv69S7b
  LJH43tkHy/YaLVYoMzV189n211qke3TBMcvaqrWAs2+ewqqCe7UvHS+JZyv7Ndgv
  qFQL05oJv21LXCbEKwOX6nk1LwIDAQABo1MwUTAdBgNVHQ4EFgQUUzKywycTKYTK
  sztsH+9E3m+1L+UwHwYDVR0jBBgwFoAUUzKywycTKYTKsztsH+9E3m+1L+UwDwYD
  VR0TAQH/BAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAgEAH6fTLX4JpuYxsqZ6l8Vy
  RaDRtpYZtYwRlho+YFkNUO/sDAv5yrNTaMt23I3f5r9SE9rvXKrpF7MmHVs8Sgkg
  kZZiuazheKItUOPxwl2cAlbRm75MVguwU8Ze9TVRoN/OdLi3MQwEghq/TQHXIl/O
  5sPg+Gjqc6xHwFWgCqvapiguLWIYkZ5JBVZSa0qbIQG7VI2MEjZJpMfAMArVLXrK
  CS8l6NvMOtZ/kZhZsBmlxFgFnaUfF3996p8YwFSEDKqzMGDhvSltVrxPjbSt7skX
  F+GBhn/OPBYn1WSINbXH1F3s2A6IFDKh2PvyVyMmaIOQsVdHTGl94vW/7vOMKL/h
  DTTajqS9MQLGa8TkW04fWWwOS6dlIcPOEmcLa0AyiA17xHOPoAuIWeaX6Tp2v4YN
  wgWA902eT6ooptPV+YeQfDsf/jqEOoREUhdZwnQWvQeZB57WfG5dCXsY2VCsEBuP
  5p4hUb4EfmzPEk69bnSRSM6q8GFPvjw+X6OnMJIbI042RdWSsEMqOaRtoo6+BHSY
  accIEdnVfD+V/63g921Uv6iAszRDRSnr4xgtdJBRBhla9ri6eEsIDjt/hY7cJAcO
  sRvLcJoPYKa9qi00M6IM5GneyMyffNrIyPxviY5DSqDGwlYYrsPMplYbGH6Cvvjh
  PX4TTYJW/hNtvPZof39aRSM=
  -----END CERTIFICATE-----
imageContentSources:
- mirrors:
  - hub.iefcu.cn/xiaoyun/openshift4-aarch64
  - quay.iefcu.cn:9443/xiaoyun/openshift4-aarch64
  source: quay.io/openshift-release-dev/ocp-release
- mirrors:
  - quay.iefcu.cn:9443/xiaoyun/openshift4-aarch64
  - hub.iefcu.cn/xiaoyun/openshift4-aarch64
  source: quay.io/openshift-release-dev/ocp-v4.0-art-dev
- mirrors:
  - registry.kcp.local:5000/kcp/openshift4-aarch64
  - quay.iefcu.cn:9443/kcp/openshift4-aarch64
  source: hub.iefcu.cn/xiaoyun/openshift4-aarch64
- mirrors:
  - registry.kcp.local:5000/kcp/openshift4-aarch64
  source: quay.iefcu.cn:9443/xiaoyun/openshift4-aarch64
kcp:
  # 手动修改release-manifests，配置kylin-logo run.sh逻辑测试
  #release: hub.iefcu.cn/xiaoyun/kcp-release:0411-tmp-test-4.9.15-arm64
  # oc adm release new升级console镜像测试
  #release: hub.iefcu.cn/xiaoyun/kcp-release:0412-test_4.9.0-rc.6-arm64-hub.iefcu.cn
  # 手动修改了镜像源为hub.iefcu.cn/xiaoyun/openshift4-aarch64测试
  release: hub.iefcu.cn/xiaoyun/kcp-release:4.9.0-rc.6-arm64-hub.iefcu.cn
