---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  #namespace: test
  labels:
    app: server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          #image: traefik/whoami:v1.6.0
          image: hub.iefcu.cn/public/containous-whoami
          ports:
            - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: server
  #namespace: test
spec:
  selector:
    app: server
  ports:
    - name: web
      protocol: TCP
      port: 80
      targetPort: 80
